server:
  port: 8080

spring:
  datasource:
    driver-class-name: ${DB_CLASSNAME}
    url: jdbc:mysql://localhost:3306/transactions_db
    username: ${DB_USERNAME}
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
