server:
  port: 8080

spring:
  datasource:
    driver-class-name: ${DB_CLASSNAME}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  FLW_SECRET_KEY: ${FLW_SECRET_KEY}
